export default function Float() {
    return (
        <div>
            <h3> FLOAT </h3>
            <p style={{float: "left", width: "20%"}}> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis convallis aliquam lacus a porta. Pellentesque ante dui, tincidunt id leo eget, ultricies sollicitudin sem. Vivamus blandit gravida ornare. Aliquam erat volutpat. Nam non lorem mattis, porttitor libero vel, condimentum tellus. Aenean consequat magna a tortor cursus, quis tempus magna tempus. Phasellus iaculis massa lobortis, mattis diam vitae, eleifend lectus. Proin pharetra sed libero eu auctor. Cras efficitur ullamcorper enim, quis imperdiet ante bibendum nec. Cras sem mi, hendrerit ac mi non, imperdiet accumsan dolor. Pellentesque mattis quam quis blandit venenatis. Nulla lobortis tellus eget purus sollicitudin elementum. Vivamus vitae ligula ut lectus lacinia auctor et a lacus. Phasellus et sodales neque. Nullam pharetra hendrerit eleifend. Donec et purus vel mi pretium tempus.</p>
            <p style={{float: "left", width: "60%"}}> Phasellus tortor urna, volutpat sed velit sed, vestibulum aliquam lorem. Pellentesque tempus metus feugiat ante commodo, ut vulputate turpis consectetur. Nullam dictum consectetur dignissim. Maecenas posuere convallis accumsan. Nam eget risus dignissim, placerat eros ut, maximus mauris. In hac habitasse platea dictumst. Donec accumsan tempus nibh, at porta nibh efficitur id. Sed at eros sit amet nunc congue aliquam. Aenean cursus interdum nisl, eu pulvinar ipsum blandit ut. Nam vel massa fringilla, interdum enim in, congue dolor. Cras viverra est nec egestas aliquet. In hac habitasse platea dictumst. Nunc augue erat, auctor et dolor a, malesuada convallis sapien. Aliquam facilisis, ante at facilisis tristique, tortor odio fermentum tellus, id accumsan lacus enim a tellus. Aenean tristique, turpis id facilisis fermentum, orci tellus tincidunt lorem, vitae gravida sem mi fringilla orci. Aenean congue non velit quis tempor. Mauris condimentum, sapien sed blandit placerat, velit nisi posuere urna, id auctor dolor ipsum at tortor. Pellentesque leo quam, tristique id semper et, pharetra id nibh.</p>
            <p style={{float: "left", width: "20%"}}> Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque nec molestie nunc. Duis dignissim quam in elementum gravida. Ut condimentum, eros vitae bibendum bibendum, erat neque semper sapien, non euismod metus tortor efficitur lacus. Suspendisse consectetur porta ipsum ac lacinia. Suspendisse sed eros pharetra, elementum ligula sit amet, malesuada sem. Suspendisse imperdiet, augue nec scelerisque feugiat, nibh ligula tristique nisl, ut malesuada quam turpis et sapien. Sed gravida risus in lobortis pharetra. Proin at fermentum elit, ac commodo ipsum. Morbi malesuada sem vitae volutpat lobortis. Vivamus vitae elementum purus, ut finibus quam. Nam condimentum consequat justo, vel porttitor felis consectetur eu. Maecenas tincidunt magna et mattis aliquam. In vestibulum faucibus nulla, sit amet porttitor quam. Ut sit amet diam commodo, dapibus risus nec, congue risus. Curabitur venenatis ut ligula vitae mattis.</p>

            <p> if a paragraph is added after the float setting, it would look like this...</p>
        </div>
    )
}